import { createSlice } from "@reduxjs/toolkit";

export const allPrerequisitionReducer = createSlice(
    { name:'adminPre',
       initialState:{
        Catagory:[],
        pincodes:[],
        carousel:[],
        cloading:false,
        cerror:null,
        ploading:false,
        perror:null,
        carloading:false,
        carerror:null
       },
       reducers:{
        
        ADMIN_CATAGORY_REQUEST(state){
            return{
                ...state,
                cloading:true
                };
              },
            ADMIN_CATAGORY_SUCCESS(state,action){
                return{
                ...state,
                cloading:false,
                Catagory:action.payload.catagories
                }
              },
            ADMIN_CATAGORY_FAIL(state,action){
                return{
                cloading:true,
                cerror:action.payload
                }
             },
             CLEAR_ACERRORS:(state)=>{
                return{
                ...state,
                cerror:null
                }
              },
              ADMIN_PINCODE_REQUEST(state){
                return{
                    ...state,
                    ploading:true
                    };
                  },
                ADMIN_PINCODE_SUCCESS(state,action){
                    return{
                    ...state,
                    ploading:false,
                    pincode:action.payload.pincodes
                    }
                  },
                ADMIN_PINCODE_FAIL(state,action){
                    return{
                    ploading:true,
                    perror:action.payload
                    }
                 },
                 CLEAR_APERRORS:(state)=>{
                    return{
                    ...state,
                    perror:null
                    }
                  },
                  ADMIN_CAROUSEL_REQUEST(state){
                    return{
                        ...state,
                        carloading:true
                        };
                      },
                    ADMIN_CAROUSEL_SUCCESS(state,action){
                        return{
                        ...state,
                        carloading:false,
                        carousel:action.payload.carousels
                        }
                      },
                    ADMIN_CAROUSEL_FAIL(state,action){
                        return{
                        carloading:true,
                        carerror:action.payload
                        }
                     },
                     CLEAR_ACARERRORS:(state)=>{
                        return{
                        ...state,
                        carerror:null
                        }
                      }
      }
    })
        export const {ADMIN_CATAGORY_FAIL,ADMIN_CATAGORY_REQUEST,ADMIN_CATAGORY_SUCCESS,CLEAR_ACERRORS,ADMIN_PINCODE_FAIL,ADMIN_PINCODE_REQUEST,ADMIN_PINCODE_SUCCESS,CLEAR_APERRORS,ADMIN_CAROUSEL_FAIL,ADMIN_CAROUSEL_REQUEST,ADMIN_CAROUSEL_SUCCESS,CLEAR_ACARERRORS}=allPrerequisitionReducer.actions
        export default allPrerequisitionReducer.reducer